name: Publish Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cargo Vendor
        run: cargo install cargo-vendor

      - name: Build project
        run: cargo build --release

      # Workaround since -C is nightly only as of 29-10-2024
      - name: Vendor dependencies
        run: cargo vendor

      - name: Copy binary to dist
        run: |
          mkdir -p dist
          cp target/release/juicerss juicerss-${{ github.ref_name }}.x86_64

      - name: Package vendor tarball
        run: tar -czf vendor-${{ github.ref_name }}.tar.gz vendor
        
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            juicerss-${{ github.ref_name }}.x86_64
            vendor-${{ github.ref_name }}.tar.xz
